remote_theme: chrisrhymes/bulma-clean-theme
#theme: bulma-clean-theme
title: Leigh Carter's Portfolio
description: A collection of projects from the Cybersecurity course that I took as well as some additional projects I've worked on individually.

permalink: pretty
github_username: lithrion
#email: sample@email.com
#linkedin reference?
markdown: kramdown
favicon: /favicon/favicon.ico
fixed_navbar: top

collections:
  htb:
    output: true
    permalik: /_htb/:path/
  class-projects:
    output: true
    permalink: /_class-projects/:path/

